admin_rpi:
    resource: "@BancarelValentinAdminRPIBundle/Resources/config/routing.yml"
    prefix:   /rpi

portefolio:
    resource: "@BancarelValentinPortefolioBundle/Resources/config/routing.yml"
    prefix:   /
